import fs from 'node:fs';
import path from 'node:path';
import solc from 'solc';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
function sources(dir: string): Record<string, { content: string }> {
  return Object.fromEntries(
    fs.readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
      const file = path.join(dir, entry.name);
      return entry.isDirectory()
        ? Object.entries(sources(file))
        : entry.name.endsWith('.sol')
          ? [[path.relative(root, file), { content: fs.readFileSync(file, 'utf8') }]]
          : [];
    }),
  );
}
const input = {
  language: 'Solidity',
  sources: sources(path.join(root, 'contracts')),
  settings: {
    optimizer: { enabled: true, runs: 200 },
    viaIR: true,
    evmVersion: 'cancun',
    // No metadata hash in the bytecode: the pinned runtime changes only when the compiled code does, never for a
    // comment or a name.
    metadata: { appendCBOR: false },
    outputSelection: {
      '*': { '': ['ast'], '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode', 'evm.gasEstimates'] },
    },
  },
};
const output = JSON.parse(solc.compile(JSON.stringify(input)));
for (const error of output.errors ?? []) {
  // The forced-ETH test intentionally selfdestructs during construction (EIP-6780).
  if (
    error.severity === 'warning' &&
    error.errorCode === '5159' &&
    error.sourceLocation?.file === 'contracts/test/ForceFunding.sol'
  )
    continue;
  process.stderr.write(error.formattedMessage);
}
if (output.errors?.some((e: any) => e.severity === 'error')) process.exit(1);
fs.mkdirSync(path.join(root, 'build'), { recursive: true });
fs.writeFileSync(path.join(root, 'build', 'compile-input.json'), JSON.stringify(input, null, 2) + '\n');
fs.writeFileSync(
  path.join(root, 'build', 'contracts.json'),
  JSON.stringify({ compiler: solc.version(), contracts: output.contracts }, null, 2) + '\n',
);
const artifact = output.contracts['contracts/HookedInCasino.sol'].HookedInCasino;
const variables = output.sources['contracts/HookedInCasino.sol'].ast.nodes.find(
  (n: any) => n.nodeType === 'ContractDefinition',
).nodes;
const immutables = Object.entries(artifact.evm.deployedBytecode.immutableReferences).map(([astId, locations]) => ({
  name: variables.find((n: any) => n.id === Number(astId)).name,
  locations,
}));
const artifactFile = path.join(root, 'client', 'contract-artifact.ts');
const artifactSource =
  '// Generated by npm run release:artifact. Ship with the trusted wallet release.\nexport default ' +
  JSON.stringify({
    compiler: solc.version(),
    abi: artifact.abi,
    runtime: '0x' + artifact.evm.deployedBytecode.object,
    immutables,
  }) +
  ';\n';
if (process.argv.includes('--update-artifact')) fs.writeFileSync(artifactFile, artifactSource);
else if (fs.readFileSync(artifactFile, 'utf8') !== artifactSource)
  throw new Error(
    'Compiled contract differs from the trusted release artifact. Review the change, then run npm run release:artifact.',
  );
console.log(`Compiled ${Object.keys(input.sources).length} Solidity sources with ${solc.version()}`);
